### ISSUE TITLE
Bug: only the `chat` command seems to be working

### ISSUE THREAD

**Issue by taurr** [bramses/chatgpt-md#81]
All the commands such as `Create new chat from template` or `Create new chat from highlighted text`, only results in an error in the console:

```
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: \ / :
    at Be (app.js:1:248617)
    at t.checkPath (app.js:1:964939)
    at t.<anonymous> (app.js:1:966824)
    at app.js:1:235927
    at Object.next (app.js:1:236032)
    at app.js:1:234948
    at new Promise (<anonymous>)
    at v (app.js:1:234693)
    at t.create (app.js:1:966712)
    at ChatTemplates.onChooseSuggestion (plugin:chatgpt-md:1182:39)
```

Ony, I don't have any special chars in my paths, and `/` can't really be removed as that is the standard separator :-)

**Comment by macdrifter** [comment]
I seem to have the same issue. The plugin throws the same error and will not create new files in any folder I specify in the configuration, including top level folders (i.e. no slashes in path)

**Comment by DenizOkcu** [comment]
fixed in relese 2.1.3
